context:
  name: git-privacy
  pypi_name: ${{ name | replace("-", "") }}
  version: 2.3.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
- url: https://pypi.io/packages/source/${{ pypi_name[0] }}/${{ pypi_name }}/${{ pypi_name }}-${{ version }}.tar.gz
  sha256: e2540a010248843fca71ea9a9177f22b62cf69f20e9292d43d24871aa7e71d74

build:
  script: python -m pip install . -vv
  number: 0
  noarch: python
  python:
    entry_points:
      - git-privacy = gitprivacy.gitprivacy:cli

requirements:
  host:
  - python >=3.6
  - pip
  - setuptools
  run:
  - python >=3.6
  - click >=7
  - gitpython
  - git-filter-repo >=2.27
  - pynacl
  # uses pkg_resources at runtime
  # https://github.com/EMPRI-DEVOPS/git-privacy/issues/41
  - setuptools

tests:
  - python:
      imports:
        - gitprivacy
      pip_check: true
  - script:
      - git-privacy --help

about:
  homepage: https://github.com/EMPRI-DEVOPS/git-privacy
  summary: Git wrapper redacting author and committer dates.
  license: BSD-2-Clause
  license_file: LICENSE
  repository: https://github.com/EMPRI-DEVOPS/git-privacy

extra:
  recipe-maintainers:
    - pavelzw
